name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Azure Web App
        run: |
          az webapp start \
          --name storyme-backend-d4bxg3afcdbreebt \
          --resource-group <your-resource-group> 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: storyme-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend
